# Generated by Django 5.1.3 on 2024-12-03 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0002_alter_spycat_salary_alter_spycat_years_of_experience"),
        ("missions", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mission",
            name="spy_cat",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="cats.spycat",
            ),
        ),
    ]
