# Generated by Django 5.1.3 on 2024-12-03 18:40

import cats.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cats", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="spycat",
            name="salary",
            field=models.IntegerField(validators=[cats.validators.validate_salary]),
        ),
        migrations.AlterField(
            model_name="spycat",
            name="years_of_experience",
            field=models.IntegerField(),
        ),
    ]
